export function getInstName(currInstType) {
  // if (currInstType)
  const arr =
    currInstType === "NIT"
      ? [
          "All",
          "NIT Jalandhar",
          "NIT Jaipur",
          "NIT Bhopal",
          "NIT Allahabad",
          "NIT Agartala",
          "NIT Calicut",
          "NIT Delhi",
          "NIT Durgapur",
          "NIT Goa",
          "NIT Hamirpur",
          "NIT Surathkal",
          "NIT Meghalaya",
          "NIT Nagaland",
          "NIT Patna",
          "NIT Puducherry",
          "NIT Raipur",
          "NIT Sikkim",
          "NIT Arunachal Pradesh",
          "NIT Jamshedpur",
          "NIT Kurukshetra",
          "NIT Manipur",
          "NIT Mizoram",
          "NIT Rourkela",
          "NIT Silchar",
          "NIT Srinagar",
          "NIT Tiruchirappalli",
          "NIT Uttarakhand",
          "NIT Warangal",
          "NIT Surat",
          "NIT Nagpur",
          "NIT Andhra Pradesh",
        ].sort()
      : [
          "All",
          "IIT Bhubaneswar",
          "IIT Bombay",
          "IIT Mandi",
          "IIT Delhi",
          "IIT Indore",
          "IIT Kharagpur",
          "IIT Hyderabad",
          "IIT Jodhpur",
          "IIT Kanpur",
          "IIT Madras",
          "IIT Gandhinagar",
          "IIT Patna",
          "IIT Roorkee",
          "IIT Dhanbad",
          "IIT Ropar",
          "IIT (BHU) Varanasi",
          "IIT Guwahati",
          "IIT Bhilai",
          "IIT Goa",
          "IIT Palakkad",
          "IIT Tirupati",
          "IIT Jammu",
          "IIT Dharwad",
          "IIT (ISM) Dhanbad",
        ].sort();
  return arr;
}
export function getBranchName(iname) {
  const arr = [
    "All",
    "Bio Technology (4 Years, Bachelor of Technology)",
    "Chemical Engineering (4 Years, Bachelor of Technology)",
    "Civil Engineering (4 Years, Bachelor of Technology)",
    "Computer Science and Engineering (4 Years, Bachelor of Technology)",
    "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
    "Industrial and Production Engineering (4 Years, Bachelor of Technology)",
    "Instrumentation and Control Engineering (4 Years, Bachelor of Technology)",
    "Mechanical Engineering (4 Years, Bachelor of Technology)",
    "Textile Technology (4 Years, Bachelor of Technology)",
    "Architecture (5 Years, Bachelor of Architecture)",
    "Electrical Engineering (4 Years, Bachelor of Technology)",
    "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
    "Materials Science and Metallurgical Engineering (4 Years, Bachelor of Technology)",
    "Planning (4 Years, Bachelor of Planning)",
    "Information Technology (4 Years, Bachelor of Technology)",
    "Production and Industrial Engineering (4 Years, Bachelor of Technology)",
    "Bio Engineering (4 Years, Bachelor of Technology)",
    "Chemistry (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
    "Electronics and Instrumentation Engineering (4 Years, Bachelor of Technology)",
    "Engineering Physics (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mathematics (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
    "Physics (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
    "Production Engineering (4 Years, Bachelor of Technology)",
    "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
    "Engineering Physics (4 Years, Bachelor of Technology)",
    "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electronics and Communication Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Computer Engineering (4 Years, Bachelor of Technology)",
    "Mining Engineering (4 Years, Bachelor of Technology)",
    "Material Science (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
    "Chemistry (5 Years, Integrated Master of Science)",
    "Mathematics (5 Years, Integrated Master of Science)",
    "Physics (5 Years, Integrated Master of Science)",
    "Bio Medical Engineering (4 Years, Bachelor of Technology)",
    "Electronics and Telecommunication Engineering (4 Years, Bachelor of Technology)",
    "Metallurgical Engineering (4 Years, Bachelor of Technology)",
    "Ceramic Engineering (4 Years, Bachelor of Technology)",
    "Ceramic Engineering and M.Tech Industrial Ceramic (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Chemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Civil Engineering and M.Tech in Transportation Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Civil Engineering and M.Tech in Water Resources (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Computer Science and Engineering and M.Tech Computer Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Computer Science and Engineering and M.Tech in Information Security (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electrical Engineering and M.Tech Control and Automation (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electrical Engineering and M.Tech Electronic Systems and Communications (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electrical Engineering and M.Tech Power Electronics and Drives (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electronics and Communication Engineering and M.Tech Communication and Network (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electronics and Instrumentation Engineering and M.Tech VLSI Design and Embedded (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Food Process Engineering (4 Years, Bachelor of Technology)",
    "Industrial Design (4 Years, Bachelor of Technology)",
    "Life Science (5 Years, Integrated Master of Science)",
    "Mechanical Engineering and M.Tech Mechatronics and Automation (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Metallurgical and Materials Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mining Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Biotechnology (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Materials Science and Engineering (4 Years, Bachelor of Technology)",
    "Biotechnology and Biochemical Engineering (4 Years, Bachelor of Technology)",
    "Mathematics and Computing (5 Years, Integrated Master of Technology)",
    "Mathematics & Computing (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
    "Mathematics and Computing (4 Years, Bachelor of Technology)",
    "Aerospace Engineering (4 Years, Bachelor of Technology)",
    "Architecture, Town and Regional Planning (5 Years, Bachelor of Architecture)",
    "Metallurgy and Materials Engineering (4 Years, Bachelor of Technology)",
    "Mathematics and Data Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Computational Mathematics (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Artificial Intelligence (4 Years, Bachelor of Technology)",
    "Computational and Data Science (4 Years, Bachelor of Technology)",
    "Civil Engineering with Specialization in Construction Technology and Management (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Computer Science and Engineering with Specialization in Cyber Security (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Computer Science and Engineering with Specialization in Data Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electrical Engineering with Specialization In Power System Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electronics and Communication Engineering with Specialization in Microelectronics and VLSI System Design (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Material Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mathematics and Computing Technology (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mechanical Engineering with Specialization in Manufacturing and Industrial Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Engineering and Computational Mechanics (4 Years, Bachelor of Technology)",
    "Civil Engineering and M. Tech. in Structural Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mechanical Engineering and M. Tech. in Mechanical System Design (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mechanical Engineering and M. Tech. in Thermal Science & Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Chemistry (4 Years, Bachelor of Science)",
    "Electrical Engineering with M.Tech. in Communications and Signal Processing (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electrical Engineering with M.Tech. in Microelectronics (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Energy Engineering with M.Tech. in Energy Systems Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Engineering Physics and M.Tech. with specialization in Nano Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mechanical Engineering and M.Tech. in Computer Integrated Manufacturing (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Metallurgical Engineering and Materials Science (4 Years, Bachelor of Technology)",
    "Metallurgical Engineering and Materials Science with M.Tech. in Ceramics and Composites (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Metallurgical Engineering and Materials Science with M.Tech. in Metallurgical Process Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Biochemical Engineering and Biotechnology (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electrical Engineering (Power and Automation) (4 Years, Bachelor of Technology)",
    "Mathematics and Computing (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Aerospace Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Agricultural and Food Engineering (4 Years, Bachelor of Technology)",
    "Agricultural and Food Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Applied Geology (5 Years, Integrated Master of Science)",
    "Biotechnology and Biochemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Civil Engineering with any of the listed specialization (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Economics (5 Years, Integrated Master of Science)",
    "Electrical Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electronics and Electrical Communication Engineering (4 Years, Bachelor of Technology)",
    "Electronics and Electrical Communication Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Exploration Geophysics (5 Years, Integrated Master of Science)",
    "Industrial and Systems Engineering (4 Years, Bachelor of Technology)",
    "Industrial and Systems Engineering with M.Tech. in Industrial and Systems Engineering and Management (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Instrumentation Engineering (4 Years, Bachelor of Technology)",
    "Manufacturing Science and Engineering (4 Years, Bachelor of Technology)",
    "Manufacturing Science and Engineering with M.Tech. in Industrial and Systems Engineering and Management (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mathematics and Computing (5 Years, Integrated Master of Science)",
    "Mechanical Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mining Safety Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Ocean Engineering and Naval Architecture (4 Years, Bachelor of Technology)",
    "Ocean Engineering and Naval Architecture (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Quality Engineering Design and Manufacturing (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Engineering Science (4 Years, Bachelor of Technology)",
    "Biological Sciences and Bioengineering (4 Years, Bachelor of Technology)",
    "Earth Sciences (4 Years, Bachelor of Science)",
    "Economics (4 Years, Bachelor of Science)",
    "Mathematics and Scientific Computing (4 Years, Bachelor of Science)",
    "Physics (4 Years, Bachelor of Science)",
    "Biological Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Biological Sciences (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
    "Civil Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electrical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Engineering Design (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mechanical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Naval Architecture and Ocean Engineering (4 Years, Bachelor of Technology)",
    "Naval Architecture and Ocean Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Applied Mathematics (5 Years, Integrated Master of Science)",
    "Geological Technology (5 Years, Integrated Master of Technology)",
    "Geophysical Technology (5 Years, Integrated Master of Technology)",
    "Polymer Science and Engineering (4 Years, Bachelor of Technology)",
    "Applied Geology (5 Years, Integrated Master of Technology)",
    "Applied Geophysics (5 Years, Integrated Master of Technology)",
    "Environmental Engineering (4 Years, Bachelor of Technology)",
    "Mineral Engineering (4 Years, Bachelor of Technology)",
    "Mining Machinery Engineering (4 Years, Bachelor of Technology)",
    "Petroleum Engineering (4 Years, Bachelor of Technology)",
    "Biochemical Engineering with M.Tech. in Biochemical Engineering and Biotechnology (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Bioengineering with M.Tech in Biomedical Technology (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Ceramic Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Civil Engineering with M.Tech. in Structural Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electrical Engineering with M.Tech. in Power Electronics (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Electronics Engineering (4 Years, Bachelor of Technology)",
    "Engineering Physics (5 Years, Integrated Master of Technology)",
    "Industrial Chemistry (5 Years, Integrated Master of Technology)",
    "Materials Science and Technology (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Metallurgical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Pharmaceutics (4 Years, Bachelor of Pharmaceutics)",
    "Pharmaceutics (5 Years, Bachelor and Master of Pharmaceutics(Dual Degree))",
    "Chemical Science and Technology (4 Years, Bachelor of Technology)",
    "Electronics and Electrical Engineering (4 Years, Bachelor of Technology)",
    "Civil Engineering and M.Tech. in Environmental Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Mechanical Engineering with M.Tech. in Manufacturing Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Metallurgical and Materials Engineering and M.Tech. in Materials Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Industrial Chemistry (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Pharmaceutical Engineering & Technology (4 Years, Bachelor of Technology)",
    "Pharmaceutical Engineering & Technology (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "BS in Mathematics (4 Years, Bachelor of Science)",
    "Environmental Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Metallurgical Engineering & Materials Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Bio Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    "Data Science and Engineering (4 Years, Bachelor of Technology)",
    "Materials Engineering (4 Years, Bachelor of Technology)",
    "Biomedical Engineering (4 Years, Bachelor of Technology)",
    "Artificial Intelligence and Data Science (4 Years, Bachelor of Technology)",
    "Civil and Infrastructure Engineering (4 Years, Bachelor of Technology)",
    "Mineral and Metallurgical Engineering (4 Years, Bachelor of Technology)",
    "Biosciences and Bioengineering (4 Years, Bachelor of Technology)",
    "Data Science and Artificial Intelligence (4 Years, Bachelor of Technology)",
    "Energy Engineering (4 Years, Bachelor of Technology)",
    "Applied Geology (4 Years, Bachelor of Science)",
    "Exploration Geophysics (4 Years, Bachelor of Science)",
    "Mathematics and Computing (4 Years, Bachelor of Science)",
    "Biotechnology and Bioinformatics (4 Years, Bachelor of Technology)",
    "Computational Engineering (4 Years, Bachelor of Technology)",
    "Industrial Chemistry (4 Years, Bachelor of Technology)",
    "Statistics and Data Science (4 Years, Bachelor of Science)",
    "Chemical Sciences (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
    "Economics (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
    "Electrical Engineering (IC Design and Technology) (4 Years, Bachelor of Technology)",
    "Chemistry with Specialization (4 Years, Bachelor of Science)",
    "Physics with Specialization (4 Years, Bachelor of Science)",
    "Mechatronics Engineering (4 Years, Bachelor of Technology)",
    "Chemical and Biochemical Engineering (4 Years, Bachelor of Technology)",
    "Interdisciplinary Sciences (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
  ];
  if (iname === "All" || iname === "") return arr;
  const ifname = getfname(iname);
  const data = {
    "Dr. B R Ambedkar National Institute of Technology, Jalandhar": [
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Industrial and Production Engineering (4 Years, Bachelor of Technology)",
      "Instrumentation and Control Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Textile Technology (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Information Technology (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology (BHU) Varanasi": [
      "Biochemical Engineering with M.Tech. in Biochemical Engineering and Biotechnology (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Bioengineering with M.Tech in Biomedical Technology (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Ceramic Engineering (4 Years, Bachelor of Technology)",
      "Ceramic Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering with M.Tech. in Structural Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering with M.Tech. in Power Electronics (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electronics Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (5 Years, Integrated Master of Technology)",
      "Industrial Chemistry (5 Years, Integrated Master of Technology)",
      "Materials Science and Technology (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mathematics and Computing (5 Years, Integrated Master of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mining Engineering (4 Years, Bachelor of Technology)",
      "Mining Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Pharmaceutics (4 Years, Bachelor of Pharmaceutics)",
      "Pharmaceutics (5 Years, Bachelor and Master of Pharmaceutics(Dual Degree))",
      "Civil Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Engineering Physics (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Industrial Chemistry (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mathematics and Computing (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Pharmaceutical Engineering & Technology (4 Years, Bachelor of Technology)",
      "Pharmaceutical Engineering & Technology (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Architecture (5 Years, Bachelor of Architecture)",
    ],
    "Indian Institute of Technology (ISM) Dhanbad": [
      "Applied Geology (5 Years, Integrated Master of Technology)",
      "Applied Geophysics (5 Years, Integrated Master of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Instrumentation Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Environmental Engineering (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (5 Years, Integrated Master of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mineral Engineering (4 Years, Bachelor of Technology)",
      "Mining Engineering (4 Years, Bachelor of Technology)",
      "Mining Machinery Engineering (4 Years, Bachelor of Technology)",
      "Petroleum Engineering (4 Years, Bachelor of Technology)",
      "Mineral and Metallurgical Engineering (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Bhilai": [
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Data Science and Artificial Intelligence (4 Years, Bachelor of Technology)",
      "Mechatronics Engineering (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Bhubaneswar": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering and M. Tech. in Structural Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Civil Engineering and M.Tech in Transportation Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering and M. Tech. in Mechanical System Design (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mechanical Engineering and M. Tech. in Thermal Science & Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering and M.Tech. in Environmental Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering and M.Tech Power Electronics and Drives (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mechanical Engineering with M.Tech. in Manufacturing Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical and Materials Engineering and M.Tech. in Materials Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical and Materials Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    ],
    "Indian Institute of Technology Bombay": [
      "Aerospace Engineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Chemistry (4 Years, Bachelor of Science)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering with M.Tech. in Communications and Signal Processing (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering with M.Tech. in Microelectronics (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Energy Engineering with M.Tech. in Energy Systems Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Engineering Physics and M.Tech. with specialization in Nano Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering and M.Tech. in Computer Integrated Manufacturing (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical Engineering and Materials Science (4 Years, Bachelor of Technology)",
      "Metallurgical Engineering and Materials Science with M.Tech. in Ceramics and Composites (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical Engineering and Materials Science with M.Tech. in Metallurgical Process Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Economics (4 Years, Bachelor of Science)",
      "BS in Mathematics (4 Years, Bachelor of Science)",
      "Environmental Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical Engineering & Materials Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Energy Engineering (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Delhi": [
      "Biochemical Engineering and Biotechnology (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Biotechnology and Biochemical Engineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (Power and Automation) (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Production and Industrial Engineering (4 Years, Bachelor of Technology)",
      "Textile Technology (4 Years, Bachelor of Technology)",
      "Engineering and Computational Mechanics (4 Years, Bachelor of Technology)",
      "Materials Engineering (4 Years, Bachelor of Technology)",
      "Energy Engineering (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Dharwad": [
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Chemical and Biochemical Engineering (4 Years, Bachelor of Technology)",
      "Civil and Infrastructure Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Interdisciplinary Sciences (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Mathematics and Computing (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Gandhinagar": [
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Materials Science and Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Materials Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    ],
    "Indian Institute of Technology Goa": [
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Guwahati": [
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Chemical Science and Technology (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Electrical Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Biosciences and Bioengineering (4 Years, Bachelor of Technology)",
      "Data Science and Artificial Intelligence (4 Years, Bachelor of Technology)",
      "Energy Engineering (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Hyderabad": [
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Engineering Science (4 Years, Bachelor of Technology)",
      "Materials Science and Metallurgical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (4 Years, Bachelor of Technology)",
      "Artificial Intelligence (4 Years, Bachelor of Technology)",
      "Biomedical Engineering (4 Years, Bachelor of Technology)",
      "Biotechnology and Bioinformatics (4 Years, Bachelor of Technology)",
      "Computational Engineering (4 Years, Bachelor of Technology)",
      "Industrial Chemistry (4 Years, Bachelor of Technology)",
      "Electrical Engineering (IC Design and Technology) (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Indore": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical Engineering and Materials Science (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Jammu": [
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Materials Science and Engineering (4 Years, Bachelor of Technology)",
      null,
      "Materials Engineering (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Jodhpur": [
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Bio Engineering (4 Years, Bachelor of Technology)",
      "Artificial Intelligence and Data Science (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil and Infrastructure Engineering (4 Years, Bachelor of Technology)",
      "Materials Engineering (4 Years, Bachelor of Technology)",
      "Chemistry with Specialization (4 Years, Bachelor of Science)",
      "Physics with Specialization (4 Years, Bachelor of Science)",
    ],
    "Indian Institute of Technology Kanpur": [
      "Aerospace Engineering (4 Years, Bachelor of Technology)",
      "Biological Sciences and Bioengineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Chemistry (4 Years, Bachelor of Science)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Earth Sciences (4 Years, Bachelor of Science)",
      "Economics (4 Years, Bachelor of Science)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Materials Science and Engineering (4 Years, Bachelor of Technology)",
      "Mathematics and Scientific Computing (4 Years, Bachelor of Science)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Physics (4 Years, Bachelor of Science)",
      "Statistics and Data Science (4 Years, Bachelor of Science)",
    ],
    "Indian Institute of Technology Kharagpur": [
      "Aerospace Engineering (4 Years, Bachelor of Technology)",
      "Aerospace Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Agricultural and Food Engineering (4 Years, Bachelor of Technology)",
      "Agricultural and Food Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Applied Geology (5 Years, Integrated Master of Science)",
      "Architecture (5 Years, Bachelor of Architecture)",
      "Biotechnology and Biochemical Engineering (4 Years, Bachelor of Technology)",
      "Biotechnology and Biochemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Chemistry (5 Years, Integrated Master of Science)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering with any of the listed specialization (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Economics (5 Years, Integrated Master of Science)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electronics and Electrical Communication Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Electrical Communication Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Exploration Geophysics (5 Years, Integrated Master of Science)",
      "Industrial and Systems Engineering (4 Years, Bachelor of Technology)",
      "Industrial and Systems Engineering with M.Tech. in Industrial and Systems Engineering and Management (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Instrumentation Engineering (4 Years, Bachelor of Technology)",
      "Manufacturing Science and Engineering (4 Years, Bachelor of Technology)",
      "Manufacturing Science and Engineering with M.Tech. in Industrial and Systems Engineering and Management (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mathematics and Computing (5 Years, Integrated Master of Science)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering with M.Tech. in any of the listed specializations (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mining Engineering (4 Years, Bachelor of Technology)",
      "Mining Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mining Safety Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Ocean Engineering and Naval Architecture (4 Years, Bachelor of Technology)",
      "Ocean Engineering and Naval Architecture (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Physics (5 Years, Integrated Master of Science)",
      "Quality Engineering Design and Manufacturing (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Applied Geology (4 Years, Bachelor of Science)",
      "Chemistry (4 Years, Bachelor of Science)",
      "Economics (4 Years, Bachelor of Science)",
      "Exploration Geophysics (4 Years, Bachelor of Science)",
      "Mathematics and Computing (4 Years, Bachelor of Science)",
      "Physics (4 Years, Bachelor of Science)",
    ],
    "Indian Institute of Technology Madras": [
      "Aerospace Engineering (4 Years, Bachelor of Technology)",
      "Aerospace Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Biological Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Biological Sciences (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Engineering Design (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Naval Architecture and Ocean Engineering (4 Years, Bachelor of Technology)",
      "Naval Architecture and Ocean Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Physics (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
    ],
    "Indian Institute of Technology Mandi": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Bio Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Data Science and Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Palakkad": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Data Science and Engineering (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Patna": [
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Artificial Intelligence and Data Science (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (4 Years, Bachelor of Science)",
    ],
    "Indian Institute of Technology Roorkee": [
      "Applied Mathematics (5 Years, Integrated Master of Science)",
      "Architecture (5 Years, Bachelor of Architecture)",
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Geological Technology (5 Years, Integrated Master of Technology)",
      "Geophysical Technology (5 Years, Integrated Master of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Polymer Science and Engineering (4 Years, Bachelor of Technology)",
      "Production and Industrial Engineering (4 Years, Bachelor of Technology)",
      "Chemistry (5 Years, Integrated Master of Science)",
      "Physics (5 Years, Integrated Master of Science)",
      "Biosciences and Bioengineering (4 Years, Bachelor of Technology)",
      "Chemical Sciences (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Economics (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Mathematics & Computing (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Physics (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Data Science and Artificial Intelligence (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Ropar": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
    ],
    "Indian Institute of Technology Tirupati": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
    ],
    "Indian School of Mines Dhanbad": [
      "Applied Geology (5 Years, Integrated Master of Technology)",
      "Applied Geophysics (5 Years, Integrated Master of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Instrumentation Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Environmental Engineering (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (5 Years, Integrated Master of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mineral Engineering (4 Years, Bachelor of Technology)",
      "Mining Engineering (4 Years, Bachelor of Technology)",
      "Mining Machinery Engineering (4 Years, Bachelor of Technology)",
      "Petroleum Engineering (4 Years, Bachelor of Technology)",
    ],
    "Malaviya National Institute of Technology Jaipur": [
      "Architecture (5 Years, Bachelor of Architecture)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
    ],
    "Maulana Azad National Institute of Technology Bhopal": [
      "Architecture (5 Years, Bachelor of Architecture)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Materials Science and Metallurgical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Planning (4 Years, Bachelor of Planning)",
      "Mathematics and Data Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
    ],
    "Motilal Nehru National Institute of Technology Allahabad": [
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Information Technology (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Production and Industrial Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Agartala": [
      "Bio Engineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Chemistry (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Instrumentation Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mathematics (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Physics (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Production Engineering (4 Years, Bachelor of Technology)",
      "Biotechnology and Biochemical Engineering (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (5 Years, Integrated Master of Technology)",
      "Mathematics & Computing (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Computational Mathematics (5 Years, Bachelor and Master of Technology (Dual Degree))",
    ],
    "National Institute of Technology Arunachal Pradesh": [
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Calicut": [
      "Architecture (5 Years, Bachelor of Architecture)",
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Production Engineering (4 Years, Bachelor of Technology)",
      "Materials Science and Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Delhi": [
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Durgapur": [
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Information Technology (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Biotechnology (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Chemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Chemistry (5 Years, Integrated Master of Science)",
    ],
    "National Institute of Technology Goa": [
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Hamirpur": [
      "Architecture (5 Years, Bachelor of Architecture)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Materials Science and Engineering (4 Years, Bachelor of Technology)",
      "Engineering Physics (4 Years, Bachelor of Technology)",
      "Mathematics and Computing (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Karnataka, Surathkal": [
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Information Technology (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Mining Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Artificial Intelligence (4 Years, Bachelor of Technology)",
      "Computational and Data Science (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Meghalaya": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Nagaland": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Instrumentation Engineering (4 Years, Bachelor of Technology)",
      "Material Science (5 Years, Bachelor of Science and Master of Science (Dual Degree))",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Patna": [
      "Architecture (5 Years, Bachelor of Architecture)",
      "Chemistry (5 Years, Integrated Master of Science)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Information Technology (4 Years, Bachelor of Technology)",
      "Mathematics (5 Years, Integrated Master of Science)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Physics (5 Years, Integrated Master of Science)",
      "Civil Engineering with Specialization in Construction Technology and Management (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Computer Science and Engineering with Specialization in Cyber Security (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Computer Science and Engineering with Specialization in Data Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering with Specialization In Power System Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electronics and Communication Engineering with Specialization in Microelectronics and VLSI System Design (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Material Science and Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mathematics and Computing Technology (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mechanical Engineering with Specialization in Manufacturing and Industrial Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
    ],
    "National Institute of Technology Puducherry": [
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Raipur": [
      "Architecture (5 Years, Bachelor of Architecture)",
      "Bio Medical Engineering (4 Years, Bachelor of Technology)",
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Telecommunication Engineering (4 Years, Bachelor of Technology)",
      "Information Technology (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical Engineering (4 Years, Bachelor of Technology)",
      "Mining Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology Sikkim": [
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Andhra Pradesh": [
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Jamshedpur": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Production and Industrial Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Engineering and Computational Mechanics (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Kurukshetra": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Information Technology (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Production and Industrial Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Manipur": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Mizoram": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Rourkela": [
      "Architecture (5 Years, Bachelor of Architecture)",
      "Bio Medical Engineering (4 Years, Bachelor of Technology)",
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Ceramic Engineering (4 Years, Bachelor of Technology)",
      "Ceramic Engineering and M.Tech Industrial Ceramic (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Chemical Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Chemistry (5 Years, Integrated Master of Science)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering and M.Tech in Transportation Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Civil Engineering and M.Tech in Water Resources (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Computer Science and Engineering and M.Tech Computer Science (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering and M.Tech in Information Security (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering and M.Tech Control and Automation (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering and M.Tech Electronic Systems and Communications (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering and M.Tech Power Electronics and Drives (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering and M.Tech Communication and Network (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Electronics and Instrumentation Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Instrumentation Engineering and M.Tech VLSI Design and Embedded (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Food Process Engineering (4 Years, Bachelor of Technology)",
      "Industrial Design (4 Years, Bachelor of Technology)",
      "Life Science (5 Years, Integrated Master of Science)",
      "Mathematics (5 Years, Integrated Master of Science)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering and M.Tech Mechatronics and Automation (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Mining Engineering (4 Years, Bachelor of Technology)",
      "Mining Engineering (5 Years, Bachelor and Master of Technology (Dual Degree))",
      "Physics (5 Years, Integrated Master of Science)",
    ],
    "National Institute of Technology, Silchar": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Instrumentation Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Srinagar": [
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Information Technology (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Tiruchirappalli": [
      "Architecture (5 Years, Bachelor of Architecture)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Instrumentation and Control Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Production Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Uttarakhand": [
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
    ],
    "National Institute of Technology, Warangal": [
      "Bio Technology (4 Years, Bachelor of Technology)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Chemistry (5 Years, Integrated Master of Science)",
      "Mathematics (5 Years, Integrated Master of Science)",
      "Physics (5 Years, Integrated Master of Science)",
    ],
    "Sardar Vallabhbhai National Institute of Technology, Surat": [
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Chemistry (5 Years, Integrated Master of Science)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Engineering (4 Years, Bachelor of Technology)",
      "Electrical Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mathematics (5 Years, Integrated Master of Science)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Physics (5 Years, Integrated Master of Science)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
    ],
    "Visvesvaraya National Institute of Technology, Nagpur": [
      "Architecture (5 Years, Bachelor of Architecture)",
      "Chemical Engineering (4 Years, Bachelor of Technology)",
      "Civil Engineering (4 Years, Bachelor of Technology)",
      "Computer Science and Engineering (4 Years, Bachelor of Technology)",
      "Electrical and Electronics Engineering (4 Years, Bachelor of Technology)",
      "Electronics and Communication Engineering (4 Years, Bachelor of Technology)",
      "Mechanical Engineering (4 Years, Bachelor of Technology)",
      "Metallurgical and Materials Engineering (4 Years, Bachelor of Technology)",
      "Mining Engineering (4 Years, Bachelor of Technology)",
    ],
  };
  var temp = data[ifname];
  temp?.unshift("All");
  return data[ifname];
  // return list[ifname];
}

export function getCatgory() {
  const arr = [
    "All",
    "OPEN",
    "OBC-NCL",
    "SC",
    "ST",
    "OPEN (PwD)",
    "SC (PwD)",
    "OBC-NCL (PwD)",
    "ST (PwD)",
    "EWS",
    "EWS (PwD)",
  ];
  return arr;
}

export function getfname(sname) {
  switch (sname) {
    case "NIT Jalandhar":
      return "Dr. B R Ambedkar National Institute of Technology, Jalandhar";
    case "NIT Jaipur":
      return "Malaviya National Institute of Technology Jaipur";
    case "NIT Bhopal":
      return "Maulana Azad National Institute of Technology Bhopal";
    case "NIT Allahabad":
      return "Motilal Nehru National Institute of Technology Allahabad";
    case "NIT Agartala":
      return "National Institute of Technology Agartala";
    case "NIT Calicut":
      return "National Institute of Technology Calicut";
    case "NIT Delhi":
      return "National Institute of Technology Delhi";
    case "NIT Durgapur":
      return "National Institute of Technology Durgapur";
    case "NIT Goa":
      return "National Institute of Technology Goa";
    case "NIT Hamirpur":
      return "National Institute of Technology Hamirpur";
    case "NIT Surathkal":
      return "National Institute of Technology Karnataka, Surathkal";
    case "NIT Meghalaya":
      return "National Institute of Technology Meghalaya";
    case "NIT Nagaland":
      return "National Institute of Technology Nagaland";
    case "NIT Patna":
      return "National Institute of Technology Patna";
    case "NIT Puducherry":
      return "National Institute of Technology Puducherry";
    case "NIT Raipur":
      return "National Institute of Technology Raipur";
    case "NIT Sikkim":
      return "National Institute of Technology Sikkim";
    case "NIT Arunachal Pradesh":
      return "National Institute of Technology Arunachal Pradesh";
    case "NIT Jamshedpur":
      return "National Institute of Technology, Jamshedpur";
    case "NIT Kurukshetra":
      return "National Institute of Technology, Kurukshetra";
    case "NIT Manipur":
      return "National Institute of Technology, Manipur";
    case "NIT Mizoram":
      return "National Institute of Technology, Mizoram";
    case "NIT Rourkela":
      return "National Institute of Technology, Rourkela";
    case "NIT Silchar":
      return "National Institute of Technology, Silchar";
    case "NIT Srinagar":
      return "National Institute of Technology, Srinagar";
    case "NIT Tiruchirappalli":
      return "National Institute of Technology, Tiruchirappalli";
    case "NIT Uttarakhand":
      return "National Institute of Technology, Uttarakhand";
    case "NIT Warangal":
      return "National Institute of Technology, Warangal";
    case "NIT Surat":
      return "Sardar Vallabhbhai National Institute of Technology, Surat";
    case "NIT Nagpur":
      return "Visvesvaraya National Institute of Technology, Nagpur";
    case "NIT Andhra Pradesh":
      return "National Institute of Technology, Andhra Pradesh";

    case "IIT Bhubaneswar":
      return "Indian Institute of Technology Bhubaneswar";
    case "IIT Bombay":
      return "Indian Institute of Technology Bombay";
    case "IIT Mandi":
      return "Indian Institute of Technology Mandi";
    case "IIT Delhi":
      return "Indian Institute of Technology Delhi";
    case "IIT Indore":
      return "Indian Institute of Technology Indore";
    case "IIT Kharagpur":
      return "Indian Institute of Technology Kharagpur";
    case "IIT Hyderabad":
      return "Indian Institute of Technology Hyderabad";
    case "IIT Jodhpur":
      return "Indian Institute of Technology Jodhpur";
    case "IIT Kanpur":
      return "Indian Institute of Technology Kanpur";
    case "IIT Madras":
      return "Indian Institute of Technology Madras";
    case "IIT Gandhinagar":
      return "Indian Institute of Technology Gandhinagar";
    case "IIT Patna":
      return "Indian Institute of Technology Patna";
    case "IIT Roorkee":
      return "Indian Institute of Technology Roorkee";
    case "IIT Dhanbad":
      return "Indian School of Mines Dhanbad";
    case "IIT Ropar":
      return "Indian Institute of Technology Ropar";
    case "IIT (BHU) Varanasi":
      return "Indian Institute of Technology (BHU) Varanasi";
    case "IIT Guwahati":
      return "Indian Institute of Technology Guwahati";
    case "IIT Bhilai":
      return "Indian Institute of Technology Bhilai";
    case "IIT Goa":
      return "Indian Institute of Technology Goa";
    case "IIT Palakkad":
      return "Indian Institute of Technology Palakkad";
    case "IIT Tirupati":
      return "Indian Institute of Technology Tirupati";
    case "IIT Jammu":
      return "Indian Institute of Technology Jammu";
    case "IIT Dharwad":
      return "Indian Institute of Technology Dharwad";
    case "IIT (ISM) Dhanbad":
      return "Indian Institute of Technology (ISM) Dhanbad";

    default:
      return "All";
  }
}
